version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bookdb_postgres
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bookapi_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: bookdb
      DB_SSLMODE: disable
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./frontend:/app/frontend

volumes:
  postgres_data:
